#!/bin/ksh

# Alerts
# Find issues
#

# Creport options.
## clush -w @NIHnet
## clushopt -qL -x dover
## errors hide
## groupby results

# Payload

# IPMI in the wrong place
[ "Supermicro" = "$(dmidecode -s system-manufacturer)" ] &&
ipmicfg -m 2>&1 |
	sed -n 's/IP=//p' |
	sed -e 's/^192\..*/LAN/' -e 's/0.0.0.0/Disabled/' -e 's/[0-9][0-9]\.[0-9][0-9]\.[0-9][0-9]\.[0-9][0-9]/on NIHnet!/' |
	egrep NIHnet |
	sed -e 's/^/SM IMPI /' 

# check that various things are installed and running.
[ ! -x /usr/bin/clamscan ] && echo clamav not installed

#[ -d /etc/.git ] && echo etckeeper is installed || echo etckeeper is not installed
[ ! -d /etc/.git ] && echo etckeeper is not enabled

[ ! -f /etc/krb5.keytab ] && echo AD Without keytab file
[ -f /etc/krb5.keytab ] && ! kinit -k  && echo AD failed join 

exit 0

