#! /bin/sh

# Check the APC UPSes
#  . find an USB UPSes
#  . report any apcuspd statuses
#
# ARF 08 August 2014
# ARF 03 November 2018

## clushopt -LNq
## post stanza2tab 'HOST TYPE UPSNAME CABLE STATUS BATTDATE LOADPCT' | column -t

# Payload

# Look to see if there is a UPS attaced via USB
lsusb | egrep Uninterruptible > /dev/null || exit 0

# Just in case
echo HOST       $(hostname -s)

# Report status for any UPS we can find.

# APC
apcaccess 2>/dev/null | 
	sed -e 's/[[:space:]]*:[[:space:]]*/	/' -e 's/[[:space:]]Percent/%/gi' -e 's/ Cable//' -e 's/Custom //' -e 's/[[:space:]]*$//' -e 's/ /,/g' |
	egrep '^(HOST|UPSNAME|STATUS|CABLE|BATTDATE|LOADPCT)[[:space:]]' |
	sed -e "1iHOST $(hostname -s)" -e '1iTYPE apcupsd' -e '$a\\'

# NUT
upsc -l 2>/dev/null | while read UPS
do
	echo HOST	$(hostname -s)
	echo UPSNAME	$UPS
	echo TYPE	NUT

	upsc "$UPS" 2>&1 | sed -n \
	-e 's/OL/ONLINE/' \
	-e 's/ups.load:.*/&%/' \
	-e 's/ups.status:/STATUS/p' \
	-e 's/battery.date:/BATTDATE/p' \
	-e 's/ups.load:/LOADPCT/p' \
	-e 's/driver.name:/CABLE/p' \

	# Finish the stanza
	echo
done

# Just in case
echo

exit

