#! /bin/ksh

### List any UID 0 accounts other than root.
### See NIST SP 800-53, AC-2
#
# Usage $0 [-q]
# 		Anthony Fletcher 16 Dec 2009

##clushopt -qL
##groupby results

# Verbose/quiet or not
verbose () { echo "$@"; }
[ "x$1" = "x-q" ] && shift && verbose () { :; }

# List any UID 0 non-root accounts
! egrep '^[^:]*:[^:]*:0:' /etc/passwd | egrep -v '^root:' && verbose No non-root UID 0 accounts

# exit with the reverse error status.
#[ $? != 0 ]

exit 0


