#!/bin/ksh

# This is a quick check on sshd binaries accross our systems. Most of
# the work is done on the admin server side rather than the client,
# because we can't trust the client. Can we trust the admin server?
#
# ARF 11 December 2018

# creport options
##clush -a
##clushopt -qL
##errors hide
######post    run-per-prefix sha256sum | sed -e 's/ -$//' | egrep -v -f "$PAYLOAD.ok" | sort
##post    run-per-prefix sha256sum | sed -e 's/ -$//' | grep -v -f  <(sed -e 's/[[:space:]].*//' "$PAYLOAD.ok")
##info If needed, update the list of MD5 checksums in sshd-binary-checksum.ok $PAYLOAD.ok
##groupby results

base64 /usr/sbin/sshd

