#!/bin/ksh

## Find any forgotton waltz backup repositories.

# Waltz is an rsync-based backup program that creates dated,
# hard-linked backup directories for each host as defined in a crental
# configiration file. 
#
# This script scans for repositories that are no long in use,
# according to the waltz configs, and should be deleted.

# creport options
## post sed -e 's/:[[:space:]]/:/' | sort -k2 | column -t
## errors hide

# Payload

# Defaults
DIRS=
quick=

# Command line
usage="Usage: $0 [-h] [-q] [-d <dir>]"
while getopts ":qhd:" arg
do
	case "$arg" in
		q) quick=1 ;; # quick scan.
		d) DIRS="$DIRS $OPTARG" ;;
		h) echo $usage; exit 0 ;;

		\:) echo "Missing option value for -$OPTARG" >&2 ; exit 1 ;;
		\?) echo "Invalid option: -$OPTARG" >&2 ; exit 1 ;;
	esac
done
shift $(($OPTIND - 1))

# Default dirs to search.
: ${DIRS:="/data /disc /export"}

ACTIVE=$(mktemp) || exit 1
trap '/bin/rm -f "$ACTIVE"' 0

# Create a list of in-use host repos
waltz -f /var/polka/etc/waltz.conf -W | 
	while read host dir hostb dirb subdir
	do
		[ "x$hostb" = "x${HOSTNAME}" ] && continue
		[[ "$hostb" = ${HOSTNAME}.* ]] && continue

		echo $dirb/$subdir
	done |
	sort | uniq > "$ACTIVE"

# Look for any host reports not in the above list
find $DIRS -maxdepth 4 -name "\latest" 2>/dev/null |
	egrep waltz |
	sed -e "s!/latest!!" |
	sed -e 's/:[[:space:]]*/:/' |
	sort | egrep -f "$ACTIVE" -v | while read D
	do
		#echo "$D	$(readlink $D/latest 2>&1)	$(du -sh $D)"
		if [ -z "$quick" ]
		then
			DU=$(du -sh $D | sed -e 's/[[:space:]].*//')
		else
			DU="-"
		fi

		echo "$D	$(readlink $D/latest 2>&1)	$DU"
	done

