.TH "creport" "1" "2019\-07\-01"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
creport \- Run  script on a collection of remote systems using clush and collect the results as a report.
.SH "SYNOPSIS"
.HP \w'\fBcreport\ [\-options]\ command\fR\ 'u
\fBcreport [\-options] command\fR
.SH "DESCRIPTION"
.PP
\fBcreport\fR
runs the following command on all the target hosts via clush and collects the results as a configurable report.
.SH "OPTIONS"

.PP
\fB\-a\fR
.RS 4
Run on all hosts (same as clush option).
.RE

.PP
\fB\-w <clush-hosts>\fR
.RS 4
Run on all specified hosts (same as clush option).
.RE

.SH "EXAMPLE"
.HP \w'\fBcreport\ \&-a\ date\fR\ 'u
\fBcreport\ \&-a date\fR
.SH "AUTHOR"
.PP
Copyright 2020- by Anthony Fletcher
.PP
Licensed under the GNU GPL
